"use strict";
const path=require("path");
const express=require("express");
const routes=require("./routes");
const app=express();
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use(express.static("public"));
app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.use("/jokebook",routes.jokebook);
const PORT=process.env.PORT||3000;
app.listen(PORT);
